---
version: "3.7"
services:
  # https://github.com/haugene/docker-transmission-openvpn
  transmission:
    image: haugene/transmission-openvpn:2.7
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=<FILL>
      - OPENVPN_CONFIG=<FILL>
      - OPENVPN_USERNAME=<FILL>
      - OPENVPN_PASSWORD=<FILL>
      - WEBPROXY_ENABLED=false
    volumes:
      - /media/downloads:/data
      - /etc/localtime:/etc/localtime:ro

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:3.0.0.2493-ls1
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/radarr:/config
      - /media/movies:/movies
      - /media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.3.687-ls166
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/sonarr:/config
      - /media/tv:/tv
      - /media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-jackett
  jackett:
    image: linuxserver/jackett:v0.12.1525-ls38
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/jackett:/config
      - /media/downloads/watch:/downloads  # transmission watch directory

  # https://github.com/ehough/docker-nfs-server
  nfs:
    image: wlad/nfs:2.2.1
    container_name: nfs
    restart: always
    cap_add:
      - SYS_ADMIN
    ports:
      - "2049:2049"
    environment:
      - NFS_EXPORT_0='/media *(rw,sync,no_subtree_check)'
    volumes:
      - /media:/media
